import { Roboto_Mono } from 'next/font/google'

import '@/app/common/styles/colors.scss'
import '@/app/common/styles/fonts.scss'
import '@/app/common/styles/globals.scss'

const roboto = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Typical Recrutment Task by Kacper Walter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        {children}
      </body>
    </html>
  )
}
